export function products() {
  const productData = [
    {
      id: 1,
      img: "assets/products/singleproduct1.jpg",
      name: "Premium Wireless HeadPhones",
      rating: "assets/ratings/rating-15.png",
      ratingCount: 124,
      currency: "Rs ",
      price: 299,
      category: "Electronics",
    },
    {
      id: 2,
      img: "assets/products/organic-cotton-t-shirt.jpeg",
      name: "Organic Cotton T-shirt",
      rating: "assets/ratings/rating-25.png",
      ratingCount: 50,
      currency: "Rs ",
      price: 500,
      category: "Clothing",
    },
    {
      id: 3,
      img: "assets/products/bluetooth-speaker.jpeg",
      name: "Bluetooth Speaker",
      rating: "assets/ratings/rating-45.png",
      ratingCount: 100,
      currency: "Rs ",
      price: 999,
      category: "Electronics",
    },
    {
      id: 4,
      img: "assets/products/leather-cossbody-bag.jpeg",
      name: "Leather Corssbody Bag",
      rating: "assets/ratings/rating-0.png",
      ratingCount: 55,
      currency: "Rs ",
      price: 899,
      category: "Accessories",
    },
    {
      id: 5,
      img: "assets/products/smart-fitness-watch.jpeg",
      name: "Smart Fitness Watch",
      rating: "assets/ratings/rating-50.png",
      ratingCount: 10,
      currency: "Rs ",
      price: 1499,
      category: "Electronics",
    },
  ];
  return productData;
}
